import unittest

class Test_test1(unittest.TestCase):
    def test_A(self):

        #id = TranscodeAudio("G:\\code\\python\\mv_pic\\mv_pic\\transcode", "", 0, 6)
        #id = TranscodeAudioVideo("G:\\code\\python\\mv_pic\\mv_pic\\transcode", "")
        #id = TranscodeVideoLoopMergeAudio("G:\\code\\python\\mv_pic\\mv_pic\\transcode", "G:\\code\\python\\mv_pic\\mv_pic\\sound", "2",".mp4")
        #id = TranscodeVideoMerge("G:\\code\\python\\mv_pic\\mv_pic\\conc", ".mp4")
        #id = TranscodeVideoOnly("G:\\code\\python\\mv_pic\\mv_pic\\Cap03", "", "13")
        #id = TranscodeVideoOnly("G:\\code\\python\\mv_pic\\mv_pic\\Cap04", "", "14")
        #id = TranscodeVideoOnly("G:\\code\\python\\mv_pic\\mv_pic\\Cap05", "", "15")
        #id = TranscodeVideoOnly("G:\\code\\python\\mv_pic\\mv_pic\\Cap06", "", "16")
        #id = TranscodeVideoOnly("G:\\code\\python\\mv_pic\\mv_pic\\Cap07", "", "17")
        #id = TranscodeVideoOnly("G:\\code\\python\\mv_pic\\mv_pic\\Cap08", "", "18")
        #id = TranscodeVideoOnly("G:\\code\\python\\mv_pic\\mv_pic\\Cap09", "", "19")
        #id = TranscodeVideoOnly("G:\\code\\python\\mv_pic\\mv_pic\\Cap10", "", "20")
        #id = TranscodeVideoOnly("G:\\code\\python\\mv_pic\\mv_pic\\Cap11", "", "21")
        #id = TranscodeVideoLoop("G:\\code\\python\\mv_pic\\mv_pic\\transcode", "5", "mp4")
        #id = TranscodeVideoLoop("G:\\code\\python\\mv_pic\\mv_pic\\play", "3", "mp4", id)
        #id = TranscodeVideo("G:\\code\\python\\mv_pic\\mv_pic\\movie", False, 1)
        #BuildDatabase("G:\\code\\python\\mv_pic\\mv_pic\\finished\\opai")
        #LoadDatabase("G:\\code\\python\\mv_pic\\mv_pic\\finished\\opai\\database.json")
        #id = 1
        #id = MakeVideoByPath("G:\\code\\python\\mv_pic\\mv_pic\\finished\\opai_merge\\1280x720", id, "Shuangxiu" )
        #id = MakeVideoByPath("G:\\code\\python\\mv_pic\\mv_pic\\finished\\opai_merge\\1920x1080", id, "Shuangxiu" )                                                        
        #id = MakeVideoByPath("G:\\code\\python\\mv_pic\\mv_pic\\finished\\opai_merge\\800x600", id, "Shuangxiu" )
        #id = MakeVideoByPath("G:\\code\\python\\mv_pic\\mv_pic\\finished\\opai_merge\\1024x768", id, "Shuangxiu" )
        #id = MakeVideoByPath("G:\\code\\python\\mv_pic\\mv_pic\\finished\\ani", id, "Shuangxiuyuehui" )
        #id = MakeVideo("G:\\code\\python\\mv_pic\\mv_pic\\finished\\05", False, id)
        #id = MakeVideo("G:\\code\\python\\mv_pic\\mv_pic\\finished\\06", False, id)
        #id = MakeVideo("G:\\code\\python\\mv_pic\\mv_pic\\finished\\07", False, id)
        #id = MakeVideo("G:\\code\\python\\mv_pic\\mv_pic\\finished\\Cap01", False, id)
        #id = MakeVideo("G:\\code\\python\\mv_pic\\mv_pic\\finished\\Cap02", False, id)
        #id = MakeVideo("G:\\code\\python\\mv_pic\\mv_pic\\finished\\Capture", False, id)
        #id = MakeVideo("G:\\code\\python\\mv_pic\\mv_pic\\Capture", False, id)
        #TransPic("G:\\code\\python\\mv_pic\\mv_pic\\char","origin", False, 300, 450)
        #MakePic("G:\\code\\python\\mv_pic\\mv_pic\\pic", False, 101, 230)
        #id = TranscodeVideoMerge("G:\\code\\python\\mv_pic\\mv_pic\\finished\\opai_merge\\1024x768\\20", ".mp4")
        #id = TranscodeVideoMerge("G:\\code\\python\\mv_pic\\mv_pic\\finished\\opai_merge\\1024x768\\Cap01", ".mp4")
        #id = TranscodeVideoMerge("G:\\code\\python\\mv_pic\\mv_pic\\finished\\opai_merge\\1024x768\\Cap02", ".mp4")
        self.fail("Not implemented")

if __name__ == '__main__':
    unittest.main()
